config/routes.rb
Rails.application.routes.draw do

  resources :bootsy
  
  devise_for :users
    resources :users, only: [:update, :show, :index]

  resources :articles, :shallow => true do
    resources :collaborations
  end

  resources :charges, only: [:new, :create]

  root 'application#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_one :author
  has_many :collaborations
  has_many :users, through: :collaborations

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  include Bootsy::Container

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = policy_scope(Article)
    authorize @articles
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.friendly.find(params[:id])
    if request.path != article_path(@article)
      redirect_to @article, status: :moved_permanently
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
    authorize @article
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    
    @article = current_user.articles.build(article_params)
    authorize @article
    @article.author_id = current_user.id

    respond_to do |format|
      if @article.save
        @article.users << current_user
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :author, :user_id, :bootsy_image_gallery_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :title, :class => 'text_field form-control'
  .form-group
    = f.label :body, :class => 'control-label col-md-2'
    .col-md-10
      = f.bootsy_area :body, :class => 'form-control', :rows => '10'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn btn-default'

app/views/articles/edit.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/index.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %tbody
    - @articles.each do |article|
      %tr
        %td=l article.created_at, format: :short
        %td.h3= link_to article.title, article
        %td
          = link_to edit_article_path(article), :class => 'btn btn-l', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
            = glyph 'pencil'
          = link_to new_article_collaboration_path(article), :class => 'btn btn-l', :title => 'share' do
            = glyph 'share'
          = link_to article_path(article), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-l', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }"  do
            = glyph 'remove'

= link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-primary'

app/views/articles/new.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/show.html.haml
- model_class = Article
.page-header
  %h1.title= @article.title

.fieldset
  = @article.body.html_safe

.form-group.text-center
  = link_to t('.back', :default => t("helpers.links.back")), articles_path, :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(@article), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), article_path(@article), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'