config/routes.rb
Rails.application.routes.draw do

  resources :bootsy
  
  devise_for :users
    resources :users, only: [:update, :show, :index]

  resources :articles, :shallow => true do
    resources :collaborations
  end

  resources :charges, only: [:new, :create]

  root 'application#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collaborations
  has_many :articles, through: :collaborations
  has_many :payments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         		
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def role?(base_role)
    role == base_role.to_s
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path(current_user)
    else
      render "devise/registrations/edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :membership)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
.row
  .col-md-12
    - if current_user.membership == nil
      = link_to 'Go Premium', new_charge_path, { :class => 'btn btn-primary btn-lg'}
%br
.row
  .col-md-2
    %h4 Name:
  .col-md-10
    = current_user.name
.row
  .col-md-2
    %h4 Email:
  .col-md-10
    = current_user.email
.row
  .col-md-2
    %h4 Membership Level:
  .col-md-10
    = current_user.membership
%br
.row
  .col-md-12
    = link_to "Back to Wikis", articles_path, class: 'btn btn-default'