config/routes.rb
Rails.application.routes.draw do

  resources :bootsy
  
  devise_for :users
    resources :users, only: [:update, :show, :index]

  resources :articles, :shallow => true do
    resources :collaborations
  end

  resources :charges, only: [:new, :create]

  root 'application#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

 # extend FriendlyId
 #  friendly_id :title, use: [:slugged, :history] 
  
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_collaboration, only: [:show, :edit, :update, :destroy]

  # GET /collaborations
  # GET /collaborations.json
  def index
    @collaborations = Collaboration.all
  end

  # GET /collaborations/1
  # GET /collaborations/1.json
  def show
  end

  # GET /collaborations/new
  def new
    @article = Article.friendly.find params[:article_id] 
    @collaboration = Collaboration.new
    @users = User.all
  end

  # GET /collaborations/1/edit
  def edit
  end

  # POST /collaborations
  # POST /collaborations.json
  def create
    @collaboration = Collaboration.new(collaboration_params)
    @article = Article.friendly.find(params[:article_id])
    @user = User.friendly.find(params[:user_id])
    @collaboration.article = @article
    @collaboration.user = @user
    respond_to do |format|
      if @collaboration.save
        format.html { redirect_to article_path(@article.slug), notice: "#{@user.email} successfully added as a collaborator." }
        format.json { render :show, status: :created, location: @collaboration }
      else
        format.html { render :new }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collaborations/1
  # PATCH/PUT /collaborations/1.json
  def update
    respond_to do |format|
      if @collaboration.update(collaboration_params)
        format.html { redirect_to @collaboration, notice: 'Collaboration was successfully updated.' }
        format.json { render :show, status: :ok, location: @collaboration }
      else
        format.html { render :edit }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collaborations/1
  # DELETE /collaborations/1.json
  def destroy
    @collaboration.destroy
    respond_to do |format|
      format.html { redirect_to collaborations_url, notice: 'Collaboration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collaboration
      @collaboration = Collaboration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collaboration_params
      params.permit(:article_id, :user_id)
    end
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/views/collaborations/_form.html.haml
= form_for [@article, @collaboration] do |f|
  - if @collaboration.errors.any?
    #error_explanation
      %h2= "#{pluralize(@collaboration.errors.count, "error")} prohibited this collaboration from being saved:"
      %ul
        - @collaboration.errors.full_messages.each do |msg|
          %li= msg       
  .form-group
    = select_tag :user_id, options_for_select(@users.collect{ |u| [u.name, u.id] }), {class: "form-control"}
  .actions
    = f.submit 'Save', :class => 'btn btn-primary'

app/views/collaborations/edit.html.haml
%h1 Editing collaboration

= render 'form'

= link_to 'Show', @collaboration
\|
= link_to 'Back', collaborations_path

app/views/collaborations/index.html.haml
%h1 Listing collaborations

%table
  %tr
    %th
    %th
    %th

  - @collaborations.each do |collaboration|
    %tr
      %td= link_to 'Show', collaboration
      %td= link_to 'Edit', edit_collaboration_path(collaboration)
      %td= link_to 'Destroy', collaboration, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Collaboration', new_collaboration_path

app/views/collaborations/new.html.haml
%h1 New Collaborator

= render 'form'
%br
= link_to t('.back', :default => t("helpers.links.back")), articles_path, :class => 'btn btn-default'

app/views/collaborations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_collaboration_path(@collaboration)
\|
= link_to 'Back', collaborations_path