config/routes.rb
Rails.application.routes.draw do

  resources :bootsy
  
  devise_for :users
    resources :users, only: [:update, :show, :index]

  resources :articles, :shallow => true do
    resources :collaborations
  end

  resources :charges, only: [:new, :create]

  root 'application#index'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
     @stripe_btn_data = {
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "RailsWiki Membership - #{current_user.name || curent_user.email}",
       plan: 'wiki-premium'
     }
  end

  def create
 
    @amount = 9_00

    # Creates a Stripe Customer object, for associating
    # with the charge

    # Associate user to an existing striper customer (if present)
    Stripe::Customer.all.each do |stripe_customer|
        if customer.email == current_user.email
            customer = stripe_customer
        else
            customer = Stripe::Customer.create(
                email: current_user.email,
                card: params[:stripeToken]
            )
        end
    end
    
    # Where the real magic happens
    charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: @amount,
     description: "RailsWiki Membership - #{current_user.email}",
     currency: 'usd',
    )

    if current_user.update_attribute(:membership, 'premium')
        flash[:success] = "Thanks, #{current_user.name || current_user.email}! Enjoy your premium membership benefits."
        redirect_to articles_path # or wherever
    end

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.haml
%h2= Thanks, you paid %strong $9!

app/views/charges/new.html.haml
= form_tag charges_path do
  / The form doesn't pass the amount to the create action, so we have to pass it manually.
  = hidden_field_tag :amount, @stripe_btn_data[:amount]
  %h4 Go premium to start sharing and making your wikis private!
  %script.stripe-button{"data-amount" => @stripe_btn_data[:amount], "data-key" => @stripe_btn_data[:key], :src => "https://checkout.stripe.com/checkout.js", "data-description" => @stripe_btn_data[:description] }